name: Publish to Packages

on:
  push:
    branches:
      - main

jobs:
  publish-plugin:
    permissions:
      contents: write
      packages: write
      deployments: write
      repository-projects: write
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - name: Publish to github packages
        env:
          GPR_USER: ${{ env.GPR_USER }}
          GPR_READ_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
        run: ./gradlew build


      - name: Extract Project Version
        id: get_version
        run: echo "::set-output name=version::$(./gradlew -q printVersion)"

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          tag: ${{ steps.get_version.outputs.version }}
