name: Build and Publish Main
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-main:
    name: Build and Publish Main
    uses: ./.github/workflows/execute-gradle-tasks-on-changed-subprojects.yml
    with:
      sub_projects_tasks: clean build publish
      parent_project_task: koverPrintCoverage
      gradle_output_handler_path: ./.github/workflows/bash-scripts/find-kover-coverage.sh

  add-kover-badge:
    name: Create Coverage Badge
    uses: Schneegans/dynamic-badges-action/.github/workflows/badges.yml@1.6.0
    with:
      auth: ${{ secrets.GIST_TOKEN }}
      gistID: 2e4bf8a120b7dd025243ba081ee72bb6
      filename: coverage-badge.json
      label: Kover
      message: ${{ steps.build-and-publish-main.outputs.root_coverage }}
      color: green