name: Build Pull Request
on:
  pull_request:
    branches:
      - '*'

jobs:
  build-pull-request:
    name: Build and Publish Pull Request
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Detect modified subprojects
        id: detect-modified-subprojects
        uses: ./.github/actions/detect-modified-projects
        with:
          project_prefixes: ktor-client,ktor-server

      - name: Execute gradle tasks on ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
        id: execute-gradle-tasks-on-projects
        uses: ./.github/actions/execute-gradle-tasks-on-projects
        with:
          projects: ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
          tasks: clean,build
          execute_on_root_anyway: true
        env:
          GPR_USER: ${{ vars.GPR_USER }}
          GPR_READ_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
