name: Build and Publish Main
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-main:
    name: Build and Publish Main
    uses: ./.github/workflows/execute-gradle-tasks-on-changed-subprojects.yml
    with:
      build_tasks: clean build publish
