name: Build and Publish Main
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-main:
    permissions:
      contents: write
    name: Build and Publish Main
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Detect modified subprojects
        uses: ./.github/actions/detect-modified-projects
        id: detect-modified-subprojects
        with:
          project_prefixes: ktor-client,ktor-server

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Execute gradle tasks on ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
        id: execute-gradle-tasks-on-projects
        uses: ./.github/actions/execute-gradle-tasks-on-projects
        with:
          projects: ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
          tasks: clean,build,publishWithShadowedJvm -xtest
          parent_project_task: koverLog release -Prelease.useAutomaticVersion=true -xtest
          execute_on_root_anyway: true
        env:
          GPR_USER: ${{ vars.GPR_USER }}
          GPR_READ_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
          GPR_WRITE_TOKEN: ${{ secrets.GPR_WRITE_TOKEN }}
