name: Build and Publish Main
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-main:
    name: Build and Publish Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Detect modified subprojects
        uses: ./.github/actions/detect-modified-projects
        id: detect-modified-subprojects
        with:
          project_prefixes: ktor-client,ktor-server

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Execute gradle tasks on ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
        id: execute-gradle-tasks-on-projects
        uses: ./.github/actions/execute-gradle-tasks-on-projects
        with:
          projects: ${{ steps.detect-modified-subprojects.outputs.modified_projects }}
          tasks: clean,build
          root_project_task: koverLog
          execute_on_root_anyway: true
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          GPR_USER: ${{ env.GPR_USER }}

      - name: Find root project kover coverage
        id: find-root-kover-coverage
        uses: ./.github/actions/find-root-kover-coverage
        with:
          gradle_output: ${{ steps.execute-gradle-tasks-on-projects.outputs.gradle_output }}
          coverage_for_green: 90

      - name: Call dynamic badges
        id: call-dynamic-badges
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 474c7fd1a50107277ce16cfbf69f4ff9
          filename: flax-ktor-plugins-kover-badge.json
          label: Kover
          message: ${{ steps.find-root-kover-coverage.outputs.kover_coverage }}
          color: ${{ steps.find-root-kover-coverage.outputs.kover_color }}
